### ISSUE TITLE
NotFound and Unauthorized Exceptions are alway logged with Anonymous User

### ISSUE THREAD

**Issue by Nimo-19** [zopefoundation/Products.SiteErrorLog#23]
Hi there.
I am not sure, if this is the right place.
I recently discovered that alle **NotFound** and **Unauthorized** Exception in the logs have and **Anonymous User** associated with them.
I encountered this in a minimal plone-5.2 buildout extending "http://dist.plone.org/release/5-latest/versions.cfg". After I removed the above Errors from the blacklist.
Is this expected behavior? I think there should be a user, but I'm not sure.
Although I'm not sure if this is the right place to ask.

Thx and greetings
Nimo

**Comment by dataflake** [comment]
This is normal:

- NotFound is raised during traversal. Authentication happens when traversal is finished. So during traversal no user information is known.

- Unauthorized is either raised if no user has logged in at all, or (this depends on the user folder) the user information can be removed from the request before the logging happens.

**Comment by Nimo-19** [comment]
Thank you very much for this explanation.
This solves my issue.
