### ISSUE TITLE
font color is the same as background color = text not readable

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.SiteErrorLog#26]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Today I had a look a reported error in the ZMI.

The error log has a black background, and - in the case of my page template error - a pre tag was used by Products.SiteErrorLog and pre tags have black font color.

See attached screenshot.

![Screenshot from 2020-11-03 16-58-44](https://user-images.githubusercontent.com/9895620/98011951-d0f8e700-1df8-11eb-9374-f72cdc354281.png)

As a workaround, you can highlight the text, so it is readable again.

### What version of Python and Zope/Addons I am using:

Python 3.7
Products.SiteErrorLog 5.4
Zope 4.5.1

Pinging @drfho - maybe there is an easy, but sustainable fix.

**Comment by drfho** [comment]
Hello, 
thanks for the hint. The pre-element needs a contextualized style if it occurs in the error-log (otherwise the block will be unvisible/black). Please, simply add  the following CSS snippet: to
https://github.com/zopefoundation/Zope/blob/d31f85f39b62a3c9c243ee886f801a911dc1320a/src/zmi/styles/resources/zmi_base.css#L857
```
.zmi-Site-Error-Log div.zmi-traceback.code pre {
	margin:inherit;
	color:inherit;
	padding:inherit;
	font-size:inherit;
	overflow:inherit
}
```
Shall I add a pull request?
Best
f

**Comment by jugmac00** [comment]
Yes, please create a pull request. Thank you for looking into this issue!
